name: Build and Release

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install setuptools wheel twine
      - name: Build wheel
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
      - name: Release
        uses: softprops/action-gh-release@v2
        with: 
          files: |
            dist/*.whl
